// Shared proxmox-clone build for Windows cloud-image templates.
//
// Each builds/windows/<name>-cloud/ directory symlinks this file as
// build.pkr.hcl and supplies clone_vm_id / vm_id / template_name in its
// variables.auto.pkrvars.hcl — the same arrangement as
// builds/linux/common/cloud-clone-build.pkr.hcl.
//
// The base template (clone_vm_id) is imported once from a Microsoft evaluation
// VHD/VHDX; see the README "Windows cloud images" section for the bootstrap.
// Cloning it skips Windows Setup entirely, which removes the slowest and by far
// the most fragile part of the ISO builds (boot_command keystroke timing).
//
// What a vendor VHD does NOT give you, unlike a Linux cloud image:
//
//   * No cloud-init equivalent preinstalled, so the image boots to an
//     interactive OOBE and waits. The answer file is injected OFFLINE into the
//     base at \Windows\Panther\unattend.xml by
//     common/scripts/bootstrap-windows-base.sh — it is NOT delivered on the CD.
//     Scanning removable media for Autounattend.xml is Windows *Setup*
//     behaviour; an already-installed image resumes at the OOBE pass, which
//     reads a fixed set of on-disk locations instead. The CD below still
//     matters: the injected unattend runs bootstrap.cmd from it.
//
//   * No QEMU guest agent. Packer discovers the VM's IP by asking the agent, so
//     without one the build waits on WinRM forever while the guest sits happily
//     on a DHCP lease. 01-install-qemu-ga.ps1 installs it during bootstrap,
//     before WinRM is needed.
//
//   * No virtio drivers. The base therefore boots SATA + e1000; virtio is
//     installed in-guest by 03-install-virtio-guest-tools.ps1, after which the
//     bus is switched by the post-processor (see switch_to_virtio).

packer {
  required_plugins {
    proxmox = {
      version = ">= 1.2.3"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

locals {
  proxmox_url                 = var.proxmox_url != null ? var.proxmox_url : vault("secret/data/packer", "PROXMOX_URL")
  proxmox_user                = var.proxmox_user != null ? var.proxmox_user : vault("secret/data/packer", "PROXMOX_USERNAME")
  proxmox_password            = var.proxmox_password != null ? var.proxmox_password : vault("secret/data/packer", "PROXMOX_PASSWORD")
  proxmox_node                = var.proxmox_node != null ? var.proxmox_node : vault("secret/data/packer", "PROXMOX_NODE")
  storage_pool                = var.storage_pool != null ? var.storage_pool : vault("secret/data/packer", "PROXMOX_STORAGE")
  iso_storage_pool            = var.iso_storage_pool != null ? var.iso_storage_pool : vault("secret/data/packer", "PROXMOX_ISO_STORAGE")
  build_username              = var.build_username != null ? var.build_username : vault("secret/data/packer", "BUILD_USERNAME")
  build_password              = var.build_password != null ? var.build_password : vault("secret/data/packer", "BUILD_PASSWORD")
  cd_label                    = "PACKER"
  cloudbase_init_url_env      = var.cloudbase_init_url != null ? var.cloudbase_init_url : ""
  cloudbase_init_checksum_env = var.cloudbase_init_checksum != null ? var.cloudbase_init_checksum : ""

  // VHD variant: specialize + oobeSystem only. See the file header for why
  // windowsPE and windows_image_index are absent.
  autounattend_xml = templatefile("${path.root}/../common/files/autounattend-vhd.pkrtpl.xml", {
    win_language   = var.win_language
    win_keyboard   = var.win_keyboard
    win_timezone   = var.win_timezone
    build_username = local.build_username
    build_password = local.build_password
  })
}

source "proxmox-clone" "windows_cloud" {
  proxmox_url              = local.proxmox_url
  username                 = local.proxmox_user
  password                 = local.proxmox_password
  node                     = local.proxmox_node
  insecure_skip_tls_verify = true

  clone_vm_id = var.clone_vm_id
  full_clone  = true

  // The plugin's default task_timeout is 1 minute, which is fine for the Linux
  // cloud clones (9-13s observed) but not for Windows: the 2022 base is 40G and
  // took 70s, so the very first run failed with "Wait timeout for ... qmclone"
  // *after the clone had actually succeeded*, leaving an orphaned VM behind.
  // 2025 is 64G and slower still.
  task_timeout = var.clone_task_timeout

  vm_id                = var.vm_id
  vm_name              = "${var.template_name}-build"
  template_name        = var.template_name
  template_description = "${var.template_description_prefix} generated by Packer on ${formatdate("YYYY-MM-DD hh:mm:ss", timestamp())} UTC"
  onboot               = true

  cpu_type = "host"
  sockets  = 1
  cores    = 4
  memory   = 8192

  qemu_agent = true

  // Disks, firmware and NIC are inherited from the base template. They are not
  // redeclared here: proxmox-clone takes the source VM's hardware, and the base
  // deliberately differs per release (2022 is MBR/SeaBIOS, 2025 is GPT/OVMF).

  // Autounattend + bootstrap + the scripts the unattend runs before WinRM is up.
  additional_iso_files {
    cd_content = {
      "/Autounattend.xml"                           = local.autounattend_xml
      "/bootstrap.cmd"                              = file("${path.root}/../common/files/bootstrap.cmd")
      "/bootstrap.ps1"                              = file("${path.root}/../common/files/bootstrap.ps1")
      "/scripts/01-install-qemu-ga.ps1"             = file("${path.root}/../common/scripts/01-install-qemu-ga.ps1")
      "/scripts/02-enable-winrm.ps1"                = file("${path.root}/../common/scripts/02-enable-winrm.ps1")
      "/scripts/10-enable-rdp.ps1"                  = file("${path.root}/../common/scripts/10-enable-rdp.ps1")
      "/scripts/12-enable-openssh.ps1"              = file("${path.root}/../common/scripts/12-enable-openssh.ps1")
      "/scripts/30-ConfigureRemotingForAnsible.ps1" = file("${path.root}/../common/scripts/30-ConfigureRemotingForAnsible.ps1")
      "/scripts/31-ansible-winrm-enablecredssp.ps1" = file("${path.root}/../common/scripts/31-ansible-winrm-enablecredssp.ps1")
    }
    cd_label         = local.cd_label
    iso_storage_pool = local.iso_storage_pool
    type             = "ide"
    index            = "3"
    unmount          = true
  }

  // VirtIO drivers + guest tools, installed in-guest (no WinPE phase to inject
  // them into). Left mounted so 03-install-virtio-guest-tools.ps1 can find it.
  additional_iso_files {
    iso_file = var.virtio_iso_file
    type     = "sata"
    index    = "1"
    unmount  = false
  }

  communicator   = "winrm"
  winrm_username = local.build_username
  winrm_password = local.build_password
  winrm_port     = 5985
  winrm_timeout  = "90m"
  winrm_use_ssl  = false
}

build {
  sources = ["source.proxmox-clone.windows_cloud"]

  provisioner "powershell" {
    inline = ["New-Item -Path 'C:\\Install' -ItemType Directory -Force | Out-Null"]
  }

  provisioner "powershell" {
    environment_vars = [
      "CLOUDBASE_INIT_URL=${local.cloudbase_init_url_env}",
      "CLOUDBASE_INIT_CHECKSUM=${local.cloudbase_init_checksum_env}",
    ]
    scripts = [
      // Must run first: everything after this depends on virtio being present
      // in the driver store for the post-build bus switch to be safe.
      "${path.root}/../common/scripts/03-install-virtio-guest-tools.ps1",
      "${path.root}/../common/scripts/10-enable-rdp.ps1",
      "${path.root}/../common/scripts/12-enable-openssh.ps1",
      "${path.root}/../common/scripts/30-ConfigureRemotingForAnsible.ps1",
      "${path.root}/../common/scripts/31-ansible-winrm-enablecredssp.ps1",
      "${path.root}/../common/scripts/11-enable-icmp.ps1",
      "${path.root}/../common/scripts/20-set-temp.ps1",
      "${path.root}/../common/scripts/59-install-winget.ps1",
      "${path.root}/../common/scripts/60-install-cloudbase-init.ps1",
      "${path.root}/../common/scripts/70-bginfo.ps1",
      "${path.root}/../common/scripts/90-customization.ps1",
      "${path.root}/../common/scripts/998-cleanup.ps1",
      // sysprep breaks WinRM; keep it last and disabled until the flow is proven.
      // "${path.root}/../common/scripts/999-sysprep.ps1",
    ]
  }

  // Flip the finished template from SATA/e1000 to virtio-scsi/virtio-net.
  // Runs against the Proxmox API after the template is created, because
  // proxmox-clone inherits the base's hardware and exposes no bus setting.
  post-processor "shell-local" {
    only   = var.switch_to_virtio ? ["proxmox-clone.windows_cloud"] : []
    inline = [
      "python3 ${path.root}/../common/scripts/switch-template-to-virtio.py --vm-id ${var.vm_id}",
    ]
  }
}
