packer {
  required_plugins {
    proxmox = {
      version = ">= 1.2.3"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

locals {
  use_iso_file                = var.iso_file != null && var.iso_file != ""
  cd_label                    = "PACKER"
  enable_cloud_init           = var.cloudbase_init_url != null && var.cloudbase_init_url != ""
  cloudbase_init_url_env      = var.cloudbase_init_url != null ? var.cloudbase_init_url : ""
  cloudbase_init_checksum_env = var.cloudbase_init_checksum != null ? var.cloudbase_init_checksum : ""

  autounattend_xml = templatefile("files/autounattend.pkrtpl.xml", {
    win_language        = var.win_language
    win_keyboard        = var.win_keyboard
    win_timezone        = var.win_timezone
    build_username      = var.build_username
    build_password      = var.build_password
    windows_image_index = var.windows_image_index
  })
}

source "proxmox-iso" "windows_server_2025_desktop_experience" {
  proxmox_url   = var.proxmox_url
  username      = var.proxmox_user
  password      = var.proxmox_password
  node          = var.proxmox_node
  vm_id         = var.vm_id
  vm_name       = "windows-server-2025-desktop-experience-template"
  template_name = "windows-server-2025-desktop-experience"

  # Homelab-friendly: avoid TLS failures when the API endpoint hostname doesn't
  # match the certificate CN/SAN.
  insecure_skip_tls_verify = true

  template_description = "Windows Server 2025 Desktop Experience template generated by Packer"
  onboot               = true
  os                   = "win10"

  cpu_type = "host"
  sockets  = 1
  cores    = 4
  memory   = 8192
  numa     = true

  machine = "q35"
  bios    = "ovmf"
  efi_config {
    efi_storage_pool  = var.storage_pool
    efi_type          = "4m"
    pre_enrolled_keys = true
  }

  # VirtIO at install time; WindowsPE gets drivers from the attached virtio ISO.
  scsi_controller         = "virtio-scsi-pci"
  qemu_agent              = true
  cloud_init              = local.enable_cloud_init
  cloud_init_storage_pool = local.enable_cloud_init ? var.storage_pool : null
  serials                 = ["socket"]

  disks {
    type         = "scsi"
    disk_size    = "80G"
    storage_pool = var.storage_pool
    format       = "raw"
  }

  network_adapters {
    model    = "virtio"
    bridge   = var.bridge
    vlan_tag = 10
  }

  boot_iso {
    iso_file         = local.use_iso_file ? var.iso_file : null
    iso_url          = local.use_iso_file ? null : var.iso_url
    iso_checksum     = local.use_iso_file ? null : var.iso_checksum
    iso_storage_pool = local.use_iso_file ? null : var.iso_storage_pool
    unmount          = true
  }

  additional_iso_files {
    cd_content = {
      "/Autounattend.xml"                           = local.autounattend_xml
      "/bootstrap.cmd"                              = file("files/bootstrap.cmd")
      "/bootstrap.ps1"                              = file("files/bootstrap.ps1")
      "/scripts/02-enable-winrm.ps1"                = file("scripts/02-enable-winrm.ps1")
      "/scripts/10-enable-rdp.ps1"                  = file("scripts/10-enable-rdp.ps1")
      "/scripts/12-enable-openssh.ps1"              = file("scripts/12-enable-openssh.ps1")
      "/scripts/30-ConfigureRemotingForAnsible.ps1" = file("scripts/30-ConfigureRemotingForAnsible.ps1")
      "/scripts/31-ansible-winrm-enablecredssp.ps1" = file("scripts/31-ansible-winrm-enablecredssp.ps1")
    }
    cd_label         = local.cd_label
    iso_storage_pool = var.iso_storage_pool
    type             = "ide"
    index            = "3"
    unmount          = true
  }

  # Attach VirtIO drivers + guest tools ISO from Proxmox storage.
  additional_iso_files {
    iso_file     = var.virtio_iso_file
    iso_url      = var.virtio_iso_file != null && var.virtio_iso_file != "" ? null : var.virtio_iso_url
    iso_checksum = var.virtio_iso_checksum
    # IDE only supports indexes 0-3; use SATA to attach an additional CD-ROM.
    type    = "sata"
    index   = "0"
    unmount = false
  }

  # Let Autounattend drive setup; WinRM becomes available once bootstrap runs.
  boot_wait = "5s"

  # First boot must prefer the Windows install ISO (ide2) over the empty disk.
  boot = "order=ide2;scsi0"

  # Windows install media often waits at "Press any key to boot from CD/DVD...".
  # Send a key a few times early in the boot; this runs only once at VM start.
  boot_command = ["<spacebar><spacebar>"]

  communicator   = "winrm"
  winrm_username = var.build_username
  winrm_password = var.build_password
  winrm_port     = 5985
  winrm_timeout  = "90m"
  winrm_use_ssl  = false
}

build {
  sources = ["source.proxmox-iso.windows_server_2025_desktop_experience"]

  provisioner "powershell" {
    inline = [
      "New-Item -Path 'C:\\Install' -ItemType Directory -Force | Out-Null",
    ]
  }

  # Initial post-install workflow. Expand this list as the template hardens.
  provisioner "powershell" {
    environment_vars = [
      "CLOUDBASE_INIT_URL=${local.cloudbase_init_url_env}",
      "CLOUDBASE_INIT_CHECKSUM=${local.cloudbase_init_checksum_env}",
    ]
    scripts = [
      "${path.root}/scripts/03-install-virtio-guest-tools.ps1",
      "${path.root}/scripts/10-enable-rdp.ps1",
      "${path.root}/scripts/12-enable-openssh.ps1",
      "${path.root}/scripts/30-ConfigureRemotingForAnsible.ps1",
      "${path.root}/scripts/31-ansible-winrm-enablecredssp.ps1",
      "${path.root}/scripts/11-enable-icmp.ps1",
      "${path.root}/scripts/20-set-temp.ps1",
      "${path.root}/scripts/59-install-winget.ps1",
      "${path.root}/scripts/60-install-cloudbase-init.ps1",
      "${path.root}/scripts/70-bginfo.ps1",
      "${path.root}/scripts/90-customization.ps1",
      "${path.root}/scripts/998-cleanup.ps1",
      # NOTE: sysprep will break WinRM connectivity; keep disabled until the rest of the flow is stable.
      # "${path.root}/scripts/999-sysprep.ps1",
    ]
  }
}
