---
- name: Template cleanup
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Run common cleanup tasks
      ansible.builtin.import_tasks: ../../../ansible/tasks/common_cleanup.yml
