packer {
  required_plugins {
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
    proxmox = {
      version = ">= 1.2.3"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

locals {
  kickstart_content = templatefile("kickstart/ks.pkrtpl.hcl", {
    root_password_hash   = bcrypt(var.root_password)
    build_username       = var.build_username
    build_password_hash  = bcrypt(var.build_password)
    ks_language          = var.ks_language
    ks_keyboard          = var.ks_keyboard
    ks_timezone          = var.ks_timezone
    ssh_public_key_root  = var.ssh_public_key_root
    ssh_public_key_build = var.ssh_public_key_build
  })
  use_iso_file = var.iso_file != null && var.iso_file != ""
}

source "proxmox-iso" "rocky_10" {
  proxmox_url          = var.proxmox_url
  username             = var.proxmox_user
  password             = var.proxmox_password
  node                 = var.proxmox_node
  vm_id                = var.vm_id
  vm_name              = "rocky-10-template"
  template_name        = "rocky-10"
  template_description = "Rocky Linux 10 template generated by Packer"
  onboot               = true

  cpu_type = "host"
  sockets  = 1
  cores    = 2
  memory   = 4096
  numa     = true

  machine = "q35"
  bios    = "ovmf"
  efi_config {
    efi_storage_pool  = var.storage_pool
    efi_type          = "4m"
    pre_enrolled_keys = true
  }
  scsi_controller         = "virtio-scsi-pci"
  qemu_agent              = true
  cloud_init              = true
  cloud_init_storage_pool = var.storage_pool
  serials                 = ["socket"]

  disks {
    type         = "scsi"
    disk_size    = "60G"
    storage_pool = var.storage_pool
    format       = "raw"
  }

  network_adapters {
    model    = "virtio"
    bridge   = var.bridge
    vlan_tag = 10
  }

  boot_iso {
    iso_file         = local.use_iso_file ? var.iso_file : null
    iso_url          = local.use_iso_file ? null : var.iso_url
    iso_checksum     = local.use_iso_file ? null : var.iso_checksum
    iso_storage_pool = local.use_iso_file ? null : var.iso_storage_pool
    unmount          = true
  }

  boot_wait = "6s"
  boot      = "order=scsi0;ide2"
  boot_command = [
    "<up>e<down><down><end> inst.text inst.ks=cdrom console=ttyS0,115200n8 <leftCtrlOn>x<leftCtrlOff>"
  ]

  ssh_username = var.build_username
  ssh_password = var.build_password
  ssh_timeout  = "15m"

  additional_iso_files {
    cd_content       = { "/ks.cfg" = local.kickstart_content }
    cd_label         = "cidata"
    iso_storage_pool = var.iso_storage_pool
    type             = "ide"
    index            = "3"
    unmount          = true
  }
}

build {
  sources = ["source.proxmox-iso.rocky_10"]

  provisioner "ansible" {
    playbook_file    = "${path.root}/ansible/configure.yml"
    user             = var.build_username
    ansible_env_vars = ["ANSIBLE_CONFIG=${path.root}/../../../../ansible.cfg"]
  }
}
