packer {
  required_plugins {
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
    proxmox = {
      version = ">= 1.2.3"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

locals {
  proxmox_url                    = var.proxmox_url != null ? var.proxmox_url : vault("secret/data/packer", "PROXMOX_URL")
  proxmox_user                   = var.proxmox_user != null ? var.proxmox_user : vault("secret/data/packer", "PROXMOX_USERNAME")
  proxmox_password               = var.proxmox_password != null ? var.proxmox_password : vault("secret/data/packer", "PROXMOX_PASSWORD")
  proxmox_node                   = var.proxmox_node != null ? var.proxmox_node : vault("secret/data/packer", "PROXMOX_NODE")
  storage_pool                   = var.storage_pool != null ? var.storage_pool : vault("secret/data/packer", "PROXMOX_STORAGE")
  iso_storage_pool               = var.iso_storage_pool != null ? var.iso_storage_pool : vault("secret/data/packer", "PROXMOX_ISO_STORAGE")
  build_username                 = var.build_username != null ? var.build_username : vault("secret/data/packer", "BUILD_USERNAME")
  build_password                 = var.build_password != null ? var.build_password : vault("secret/data/packer", "BUILD_PASSWORD")
  root_password                  = var.root_password != null ? var.root_password : vault("secret/data/packer", "ROOT_PASSWORD")
  ssh_public_key_root_authorized = trimspace(var.ssh_public_key_root_authorized != null ? var.ssh_public_key_root_authorized : vault("secret/data/packer", "SSH_PUBLIC_KEY_ROOT_AUTHORIZED"))
  ssh_public_key_build           = trimspace(var.ssh_public_key_build != null ? var.ssh_public_key_build : vault("secret/data/packer", "SSH_PUBLIC_KEY_BUILD"))
  kickstart_content = templatefile("kickstart/ks.pkrtpl.hcl", {
    root_password_hash             = bcrypt(local.root_password)
    build_username                 = local.build_username
    build_password_hash            = bcrypt(local.build_password)
    ks_language                    = var.ks_language
    ks_keyboard                    = var.ks_keyboard
    ks_timezone                    = var.ks_timezone
    ssh_public_key_root_authorized = local.ssh_public_key_root_authorized
    ssh_public_key_build           = local.ssh_public_key_build
  })
}

source "proxmox-iso" "rhel_10" {
  proxmox_url          = local.proxmox_url
  username             = local.proxmox_user
  password             = local.proxmox_password
  node                 = local.proxmox_node
  vm_id                = var.vm_id
  vm_name              = "rhel-10-template"
  template_name        = "rhel-10"
  template_description = "RHEL 10 template generated by Packer on ${formatdate("YYYY-MM-DD hh:mm:ss", timestamp())} UTC"
  onboot               = true

  cpu_type = "host"
  sockets  = 1
  cores    = 2
  memory   = 4096
  numa     = true

  machine = "q35"
  bios    = "ovmf"
  efi_config {
    efi_storage_pool  = local.storage_pool
    efi_type          = "4m"
    pre_enrolled_keys = true
  }
  scsi_controller         = "virtio-scsi-pci"
  qemu_agent              = true
  cloud_init              = true
  cloud_init_storage_pool = local.storage_pool
  serials                 = ["socket"]

  disks {
    type         = "scsi"
    disk_size    = "60G"
    storage_pool = local.storage_pool
    format       = "raw"
  }

  network_adapters {
    model    = "virtio"
    bridge   = var.bridge
    vlan_tag = 10
  }

  boot_iso {
    iso_file = var.iso_file
    unmount  = true
  }

  boot_wait = "6s"
  boot      = "order=scsi0;ide2"
  boot_command = [
    "<up>e<down><down><end> inst.text inst.ks=cdrom console=ttyS0,115200n8 <leftCtrlOn>x<leftCtrlOff>"
  ]

  ssh_username = local.build_username
  ssh_private_key_file = var.ssh_private_key_file
  ssh_timeout  = "15m"

  additional_iso_files {
    cd_content       = { "/ks.cfg" = local.kickstart_content }
    cd_label         = "cidata"
    iso_storage_pool = local.iso_storage_pool
    type             = "ide"
    index            = "3"
    unmount          = true
  }
}

build {
  sources = ["source.proxmox-iso.rhel_10"]

  provisioner "ansible" {
    playbook_file    = "${path.root}/ansible/configure.yml"
    user             = local.build_username
    ansible_env_vars = ["ANSIBLE_CONFIG=${path.root}/../../../../ansible.cfg", "OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES", "ANSIBLE_HASHI_VAULT_VALIDATE_CERTS=false"]
  }
}
