packer {
  required_plugins {
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
    proxmox = {
      version = ">= 1.2.3"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

locals {
  proxmox_url      = var.proxmox_url != null ? var.proxmox_url : vault("secret/data/packer", "PROXMOX_URL")
  proxmox_user     = var.proxmox_user != null ? var.proxmox_user : vault("secret/data/packer", "PROXMOX_USERNAME")
  proxmox_password = var.proxmox_password != null ? var.proxmox_password : vault("secret/data/packer", "PROXMOX_PASSWORD")
  proxmox_node     = var.proxmox_node != null ? var.proxmox_node : vault("secret/data/packer", "PROXMOX_NODE")
  storage_pool     = var.storage_pool != null ? var.storage_pool : vault("secret/data/packer", "PROXMOX_STORAGE")
  iso_storage_pool = var.iso_storage_pool != null ? var.iso_storage_pool : vault("secret/data/packer", "PROXMOX_ISO_STORAGE")
  build_username   = var.build_username != null ? var.build_username : vault("secret/data/packer", "BUILD_USERNAME")
}

source "proxmox-clone" "ubuntu_24_04_cloud" {
  proxmox_url              = local.proxmox_url
  username                 = local.proxmox_user
  password                 = local.proxmox_password
  insecure_skip_tls_verify = true

  node        = local.proxmox_node
  clone_vm_id = var.clone_vm_id
  full_clone  = true
  vm_id       = var.vm_id
  vm_name     = "${var.template_name}-build"

  template_name        = var.template_name
  template_description = "Ubuntu 24.04 cloud image template generated by Packer on ${formatdate("YYYY-MM-DD hh:mm:ss", timestamp())} UTC"
  tags                 = "ubuntu;cloud-init;packer"

  cpu_type = "host"
  sockets  = 1
  cores    = var.cores
  memory   = var.memory_mb
  numa     = true
  os       = "l26"

  machine                 = "q35"
  bios                    = "ovmf"
  scsi_controller         = "virtio-scsi-pci"
  qemu_agent              = true
  cloud_init              = true
  cloud_init_storage_pool = local.storage_pool
  serials                 = ["socket"]
  boot                    = "order=scsi0"

  efi_config {
    efi_storage_pool  = local.storage_pool
    efi_type          = "4m"
    pre_enrolled_keys = true
  }

  network_adapters {
    model    = "virtio"
    bridge   = var.bridge
    vlan_tag = var.vlan_tag
  }

  ipconfig {
    ip = "dhcp"
  }

  additional_iso_files {
    cd_content = {
      "/meta-data" = "instance-id: ${var.template_name}-packer\nlocal-hostname: ${var.template_name}-packer\n"
      "/user-data" = <<-EOF
#cloud-config
package_update: true
packages:
  - qemu-guest-agent
users:
  - default
  - name: ${local.build_username}
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${var.ssh_public_key_build}
ssh_pwauth: false
runcmd:
  - systemctl enable --now qemu-guest-agent
EOF
    }
    cd_label         = "cidata"
    iso_storage_pool = local.iso_storage_pool
    type             = "ide"
    index            = "3"
    unmount          = true
  }

  ssh_username         = local.build_username
  ssh_private_key_file = var.ssh_private_key_file
  ssh_timeout          = "20m"
}

build {
  sources = ["source.proxmox-clone.ubuntu_24_04_cloud"]

  provisioner "ansible" {
    playbook_file    = "${path.root}/../24.04/ansible/configure.yml"
    user             = local.build_username
    ansible_env_vars = ["ANSIBLE_CONFIG=${path.root}/../../../../ansible.cfg", "OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES", "ANSIBLE_HASHI_VAULT_VALIDATE_CERTS=false"]
  }

  post-processor "shell-local" {
    environment_vars = [
      "PROXMOX_URL=${local.proxmox_url}",
      "PROXMOX_USERNAME=${local.proxmox_user}",
      "PROXMOX_PASSWORD=${local.proxmox_password}",
      "PROXMOX_NODE=${local.proxmox_node}",
      "PROXMOX_VM_ID=${var.vm_id}",
    ]
    command = "${path.root}/scripts/finalize-template-config.py"
  }
}

variable "proxmox_url" {
  type        = string
  description = "Proxmox API URL, e.g. https://proxmox.example.com:8006/api2/json"
  default     = null
}

variable "proxmox_user" {
  type        = string
  description = "Proxmox API user, e.g. root@pam"
  default     = null
}

variable "proxmox_password" {
  type        = string
  description = "Proxmox API password"
  sensitive   = true
  default     = null
}

variable "proxmox_node" {
  type        = string
  description = "Proxmox node name"
  default     = null
}

variable "storage_pool" {
  type        = string
  description = "Proxmox storage pool name"
  default     = null
}

variable "iso_storage_pool" {
  type        = string
  description = "Proxmox storage pool for temporary Packer seed ISO"
  default     = null
}

variable "bridge" {
  type        = string
  description = "Proxmox bridge name"
  default     = "vmbr0"
}

variable "vlan_tag" {
  type        = number
  description = "Proxmox VLAN tag for the template NIC"
  default     = 10
}

variable "clone_vm_id" {
  type        = number
  description = "VMID of the imported Ubuntu cloud-image base template"
}

variable "vm_id" {
  type        = number
  description = "Proxmox VMID for the final cloud image template"
}

variable "template_name" {
  type        = string
  description = "Final Proxmox template name"
  default     = "ubuntu-24-04-cloud"
}

variable "memory_mb" {
  type        = number
  description = "Template VM memory in MiB"
  default     = 4096
}

variable "cores" {
  type        = number
  description = "Template VM cores"
  default     = 2
}

variable "build_username" {
  type        = string
  description = "Cloud-init user used by Packer for provisioning"
  default     = "ubuntu"
}

variable "ssh_private_key_file" {
  type        = string
  description = "Path to the private key injected by Packer for provisioning"
  default     = "~/.ssh/id_ed25519"
}

variable "ssh_public_key_build" {
  type        = string
  description = "Ephemeral public key generated by build.py for Packer clone provisioning"
  default     = null
}

variable "ks_language" {
  type        = string
  description = "Shared Linux build variable; unused by cloud-image clone builds"
  default     = null
}

variable "ks_keyboard" {
  type        = string
  description = "Shared Linux build variable; unused by cloud-image clone builds"
  default     = null
}

variable "ks_timezone" {
  type        = string
  description = "Shared Linux build variable; unused by cloud-image clone builds"
  default     = null
}
