---
- name: Template cleanup
  hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Run common cleanup tasks
      ansible.builtin.import_tasks: ../../../ansible/tasks/common_cleanup.yml
