packer {
  required_plugins {
    proxmox = {
      version = ">= 1.2.3"
      source  = "github.com/hashicorp/proxmox"
    }
    windows-update = {
      version = ">= 0.18.0"
      source  = "github.com/rgl/windows-update"
    }
  }
}

locals {
  proxmox_url      = var.proxmox_url != null ? var.proxmox_url : vault("secret/data/packer", "PROXMOX_URL")
  proxmox_user     = var.proxmox_user != null ? var.proxmox_user : vault("secret/data/packer", "PROXMOX_USERNAME")
  proxmox_password = var.proxmox_password != null ? var.proxmox_password : vault("secret/data/packer", "PROXMOX_PASSWORD")
  proxmox_node     = var.proxmox_node != null ? var.proxmox_node : vault("secret/data/packer", "PROXMOX_NODE")
  storage_pool     = var.storage_pool != null ? var.storage_pool : vault("secret/data/packer", "PROXMOX_STORAGE")
  iso_storage_pool = var.iso_storage_pool != null ? var.iso_storage_pool : vault("secret/data/packer", "PROXMOX_ISO_STORAGE")
  build_username   = var.build_username != null ? var.build_username : vault("secret/data/packer", "BUILD_USERNAME")
  build_password   = var.build_password != null ? var.build_password : vault("secret/data/packer", "BUILD_PASSWORD")
  use_iso_file     = var.iso_file != null && var.iso_file != ""
  cd_label         = "PACKER"

  autounattend_xml = templatefile("files/autounattend.pkrtpl.xml", {
    win_language        = var.win_language
    win_keyboard        = var.win_keyboard
    win_timezone        = var.win_timezone
    build_username      = local.build_username
    build_password      = local.build_password
    windows_image_index = var.windows_image_index
  })
}

source "proxmox-iso" "windows_server_2022_core" {
  proxmox_url   = local.proxmox_url
  username      = local.proxmox_user
  password      = local.proxmox_password
  node          = local.proxmox_node
  vm_id         = var.vm_id
  vm_name       = "windows-server-2022-core-template"
  template_name = "windows-server-2022-core"

  # Homelab-friendly: avoid TLS failures when the API endpoint hostname doesn't
  # match the certificate CN/SAN.
  insecure_skip_tls_verify = true

  template_description = "Windows Server 2022 Core template generated by Packer on ${formatdate("YYYY-MM-DD hh:mm:ss 'UTC'", timestamp())}"
  onboot               = true

  cpu_type = "host"
  sockets  = 1
  cores    = 4
  memory   = 8192
  numa     = true

  machine = "q35"
  bios    = "ovmf"
  efi_config {
    efi_storage_pool  = local.storage_pool
    efi_type          = "4m"
    pre_enrolled_keys = true
  }

  # VirtIO at install time; WindowsPE gets drivers from the attached virtio ISO.
  scsi_controller = "virtio-scsi-pci"
  qemu_agent      = true
  serials         = ["socket"]

  disks {
    type         = "scsi"
    disk_size    = "80G"
    storage_pool = local.storage_pool
    format       = "raw"

    # discard=on so space freed inside the guest is punched out of the backing
    # store instead of being held forever. Without it a template disk only ever
    # grows: the ~GBs of Windows Update payload that 998-cleanup deletes stayed
    # allocated. Requires a backing store that can punch holes -- nas-datastore01
    # is NFS 4.2, which can. ssd=true advertises the disk as non-rotational so
    # Windows issues TRIM (and skips scheduled defrag) rather than sitting on it.
    discard = true
    ssd     = true
  }

  network_adapters {
    model    = "virtio"
    bridge   = var.bridge
    vlan_tag = 10
  }

  boot_iso {
    iso_file         = local.use_iso_file ? var.iso_file : null
    iso_url          = local.use_iso_file ? null : var.iso_url
    iso_checksum     = local.use_iso_file ? null : var.iso_checksum
    iso_storage_pool = local.use_iso_file ? null : local.iso_storage_pool
    unmount          = true
  }

  additional_iso_files {
    cd_content = {
      "/Autounattend.xml" = local.autounattend_xml
      "/bootstrap.cmd"    = file("../common/files/bootstrap.cmd")
      "/bootstrap.ps1"    = file("../common/files/bootstrap.ps1")
      # bootstrap.ps1 installs the guest agent before WinRM: Packer discovers the
      # VM's IP through the agent, so it has to exist before the listener matters.
      # Full guest tools FIRST: the QEMU agent reaches the host over a
      # virtio-serial channel and the agent-only MSI does not install that
      # driver, so without this Packer never discovers the VM IP.
      "/scripts/10-install-virtio-guest-tools.ps1" = file("../common/scripts/10-install-virtio-guest-tools.ps1")
      "/scripts/00-install-qemu-ga.ps1"            = file("../common/scripts/00-install-qemu-ga.ps1")
      # NOTE: only the scripts bootstrap.ps1 actually runs are shipped here.
      # Everything else runs as a provisioner, where Packer uploads its own
      # copy - shipping those on the CD staged files nothing ever executed.
      # In particular 24-configure-winrm-for-ansible.ps1 is a provisioner: the
      # HTTPS/CredSSP config it applies is for CLONES, not for the build.
      "/scripts/01-enable-winrm.ps1" = file("../common/scripts/01-enable-winrm.ps1")
      # 11-install-lab-ca.ps1 reads this off the CD and throws if it is absent.
      "/root_ca_bundle.pem" = file("../common/files/root_ca_bundle.pem")
    }
    cd_label         = local.cd_label
    iso_storage_pool = local.iso_storage_pool
    type             = "ide"
    index            = "3"
    unmount          = true
  }

  # Attach VirtIO drivers + guest tools ISO from Proxmox storage.
  additional_iso_files {
    iso_file     = var.virtio_iso_file
    iso_url      = var.virtio_iso_file != null && var.virtio_iso_file != "" ? null : var.virtio_iso_url
    iso_checksum = var.virtio_iso_checksum
    # IDE only supports indexes 0-3; use SATA to attach an additional CD-ROM.
    type    = "sata"
    index   = "0"
    unmount = false
  }

  # Let Autounattend drive setup; WinRM becomes available once bootstrap runs.
  # Start typing early: keys sent before the prompt are harmlessly discarded,
  # so the failure mode to avoid is being LATE, not early.
  boot_wait = "3s"

  # First boot must prefer the Windows install ISO (ide2) over the empty disk.
  boot = "order=ide2;scsi0"

  # Windows install media stops at "Press any key to boot from CD or DVD..." and
  # waits only ~5s. OVMF POST on q35 with a 4m EFI disk is slow and varies run to
  # run, so a single burst at a fixed offset is a coin flip -- and it lost every
  # time: ["<spacebar><spacebar>"] at boot_wait=5s fired before the prompt was up,
  # the window expired, and the VM fell through to "BdsDxe: No bootable option or
  # device was found". That is why no Windows ISO template had ever built.
  #
  # Type a key once a second for ~45s instead, so the prompt cannot be missed
  # whatever POST costs. Keys before the prompt are dropped; keys after it are
  # absorbed by Setup, which is driven entirely by the answer file. Worst case
  # this adds a minute to an hour-long build.
  boot_command = [
    # Phase 1 -- get past "Press any key to boot from CD or DVD" (~5s window at
    # an unpredictable offset). Spacebar is deliberately non-committal so it
    # cannot pick anything by accident if a menu is already up.
    join("", [for _i in range(45) : "<spacebar><wait>"]),
    # Phase 2 -- those keystrokes also cancel Windows Boot Manager's auto-select
    # countdown, which then parks on "Windows Setup [EMS Enabled]" FOREVER
    # waiting for ENTER (confirmed on the console: the menu was still up when
    # boot_command finished, and the build would have burned the full 90m WinRM
    # timeout there). Commit the highlighted entry explicitly. Harmless if the
    # menu already advanced -- Setup absorbs the keys, the answer file drives it.
    "<wait5><enter><wait5><enter>",
  ]

  communicator   = "winrm"
  winrm_username = local.build_username
  winrm_password = local.build_password
  winrm_port     = 5985
  winrm_timeout  = "90m"
  winrm_use_ssl  = false
}

build {
  sources = ["source.proxmox-iso.windows_server_2022_core"]
  # FIRST, before anything else - including Windows Update. The bootstrap
  # scripts exit 0 by design (a non-zero exit from a first-logon command aborts
  # the logon sequence) and record their verdict in marker files; this reads
  # them. It has to run before the update pass or a broken bootstrap is only
  # discovered ~35 minutes later, which defeats the point of failing fast.
  provisioner "powershell" {
    scripts = [
      "${path.root}/../common/scripts/04-assert-bootstrap-clean.ps1",
    ]
  }


  # Fully patch the image FIRST so ISO templates ship current and the rest of
  # the config lands on a patched OS (cleanup stays last). The rgl plugin drives
  # the Windows Update Agent and reboots as needed until no updates remain.
  provisioner "windows-update" {
    search_criteria = "IsInstalled=0"
    filters = [
      "exclude:$_.Title -like '*Preview*'",
      "include:$true",
    ]
  }

  provisioner "powershell" {
    inline = [
      "New-Item -Path 'C:\\Install' -ItemType Directory -Force | Out-Null",
    ]
  }

  # Post-install workflow. This list is deliberately IDENTICAL across every
  # Windows image -- ISO and cloud, Core and Desktop Experience -- so a template
  # differs only in how it was installed, never in what it contains. Scripts all
  # live in builds/windows/common/scripts; there are no per-build copies.
  provisioner "powershell" {
    scripts = [
      "${path.root}/../common/scripts/11-install-lab-ca.ps1",
      "${path.root}/../common/scripts/20-enable-rdp.ps1",
      "${path.root}/../common/scripts/21-enable-openssh.ps1",
      "${path.root}/../common/scripts/22-enable-icmp.ps1",
      "${path.root}/../common/scripts/23-enable-ems-serial.ps1",
      "${path.root}/../common/scripts/24-configure-winrm-for-ansible.ps1",
      "${path.root}/../common/scripts/30-set-temp.ps1",
      "${path.root}/../common/scripts/53-install-winget.ps1",
      "${path.root}/../common/scripts/60-install-cloudbase-init.ps1",
      "${path.root}/../common/scripts/80-bginfo.ps1",
      "${path.root}/../common/scripts/81-customization.ps1",
      "${path.root}/../common/scripts/998-cleanup.ps1",
      # NOTE: sysprep breaks WinRM connectivity; it must be the final provisioner
      # and stays disabled until the rest of the flow is proven.
      # "${path.root}/../common/scripts/999-sysprep.ps1",
    ]
  }
}
