#!/usr/bin/env python3
"""Set a freshly built Proxmox template's description with a local-time build date.

Reads PROXMOX_URL / PROXMOX_USERNAME / PROXMOX_PASSWORD / PROXMOX_NODE /
PROXMOX_VM_ID from the environment (as provided by the packer shell-local
post-processor), fetches the template's name, and writes:
    "<name> template generated by Packer on <YYYY-MM-DD HH:MM:SS CST/CDT>"
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

if __name__ == "__main__":
    repo_root = next(
        (p for p in Path(__file__).resolve().parents if (p / ".venv").is_dir()),
        Path(__file__).resolve().parents[4],
    )
    venv_python = repo_root / ".venv" / "bin" / "python3"
    if venv_python.is_file() and os.access(venv_python, os.X_OK) and sys.executable != str(venv_python):
        os.execv(str(venv_python), [str(venv_python)] + sys.argv)

import urllib.parse
from datetime import datetime
from zoneinfo import ZoneInfo

from proxmoxer import ProxmoxAPI


def require(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise SystemExit(f"{name} is required")
    return value


def main() -> int:
    url = require("PROXMOX_URL")
    parsed = urllib.parse.urlparse(url)
    prox = ProxmoxAPI(
        parsed.hostname,
        user=require("PROXMOX_USERNAME"),
        password=require("PROXMOX_PASSWORD"),
        verify_ssl=False,
        port=parsed.port or 443,
    )
    node = require("PROXMOX_NODE")
    vm_id = int(require("PROXMOX_VM_ID"))

    config = prox.nodes(node).qemu(vm_id).config.get()
    name = config.get("name", f"vmid-{vm_id}")
    stamp = datetime.now(ZoneInfo("America/Chicago")).strftime("%Y-%m-%d %H:%M:%S %Z")
    description = f"{name} template generated by Packer on {stamp}"
    prox.nodes(node).qemu(vm_id).config.put(description=description)
    print(f"VMID {vm_id}: description set: {description}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
