---
- name: Template cleanup
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - ../../../ansible/vars/rhel_registration.yml
  tasks:
    - name: Run Red Hat registration tasks
      ansible.builtin.import_tasks: ../../../ansible/tasks/rhel_registration.yml

    - name: Run common cleanup tasks
      ansible.builtin.import_tasks: ../../../ansible/tasks/common_cleanup.yml
