// Shared proxmox-clone build for RHEL/Rocky cloud (qcow2) image templates.
// Each builds/linux/<family>/<release>-cloud/ directory symlinks this file as
// build.pkr.hcl and supplies clone_vm_id / vm_id / template_name / tags /
// rhel_subscription in its variables.auto.pkrvars.hcl. The base template
// (clone_vm_id) is created from the upstream qcow2 by
// builds/linux/common/scripts/bootstrap-base-template.py.
packer {
  required_plugins {
    ansible = {
      version = ">= 1.1.0"
      source  = "github.com/hashicorp/ansible"
    }
    proxmox = {
      version = ">= 1.2.3"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

locals {
  proxmox_url      = var.proxmox_url != null ? var.proxmox_url : vault("secret/data/packer", "PROXMOX_URL")
  proxmox_user     = var.proxmox_user != null ? var.proxmox_user : vault("secret/data/packer", "PROXMOX_USERNAME")
  proxmox_password = var.proxmox_password != null ? var.proxmox_password : vault("secret/data/packer", "PROXMOX_PASSWORD")
  proxmox_node     = var.proxmox_node != null ? var.proxmox_node : vault("secret/data/packer", "PROXMOX_NODE")
  storage_pool     = var.storage_pool != null ? var.storage_pool : vault("secret/data/packer", "PROXMOX_STORAGE")
  iso_storage_pool = var.iso_storage_pool != null ? var.iso_storage_pool : vault("secret/data/packer", "PROXMOX_ISO_STORAGE")
  build_username   = var.build_username != null ? var.build_username : vault("secret/data/packer", "BUILD_USERNAME")

  // Parity with the kickstart builds: same root/build passwords and the
  // same authorized keys (persistent root key + the ephemeral build key).
  root_password_hash             = bcrypt(vault("secret/data/packer", "ROOT_PASSWORD"))
  build_password_hash            = bcrypt(vault("secret/data/packer", "BUILD_PASSWORD"))
  ssh_public_key_root_authorized = trimspace(vault("secret/data/packer", "SSH_PUBLIC_KEY_ROOT_AUTHORIZED"))

  // RHEL cloud images ship unregistered with no enabled repos and no
  // qemu-guest-agent; register at cloud-init config stage (rh_subscription)
  // so the final-stage package install can pull qemu-guest-agent — packer
  // cannot discover the VM's IP without the agent. The seed ISO is
  // unmounted and deleted by packer after the build.
  rh_subscription_block = var.rhel_subscription ? join("\n", [
    "rh_subscription:",
    "  username: ${vault("secret/data/packer", "redhat_username")}",
    "  password: ${vault("secret/data/packer", "redhat_password")}",
    "  auto-attach: true",
  ]) : ""

  // Seed cloud-config lives in cloud-seed-user-data.pkrtpl (kickstart-style
  // template file); parity with the ISO builds is applied by
  // builds/linux/ansible/cloud_configure.yml.
  seed_user_data = templatefile("${path.root}/../../common/cloud-seed-user-data.pkrtpl", {
    rh_subscription_block          = local.rh_subscription_block
    build_username                 = local.build_username
    root_password_hash             = local.root_password_hash
    build_password_hash            = local.build_password_hash
    ssh_public_key_root_authorized = local.ssh_public_key_root_authorized
    ssh_public_key_build           = var.ssh_public_key_build
  })
}

source "proxmox-clone" "cloud" {
  proxmox_url              = local.proxmox_url
  username                 = local.proxmox_user
  password                 = local.proxmox_password
  insecure_skip_tls_verify = true

  node        = local.proxmox_node
  clone_vm_id = var.clone_vm_id
  full_clone  = true
  vm_id       = var.vm_id
  vm_name     = "${var.template_name}-build"

  template_name        = var.template_name
  template_description = "${var.template_name} cloud image template generated by Packer on ${formatdate("YYYY-MM-DD hh:mm:ss", timestamp())} UTC"
  tags                 = var.tags

  cpu_type = "host"
  sockets  = 1
  cores    = var.cores
  memory   = var.memory_mb
  numa     = true
  os       = "l26"

  machine                 = "q35"
  bios                    = "ovmf"
  scsi_controller         = "virtio-scsi-pci"
  qemu_agent              = true
  cloud_init              = true
  cloud_init_storage_pool = local.storage_pool
  serials                 = ["socket"]
  boot                    = "order=scsi0"

  efi_config {
    efi_storage_pool  = local.storage_pool
    efi_type          = "4m"
    pre_enrolled_keys = true
  }

  network_adapters {
    model    = "virtio"
    bridge   = var.bridge
    vlan_tag = var.vlan_tag
  }

  ipconfig {
    ip = "dhcp"
  }

  additional_iso_files {
    cd_content = {
      "/meta-data" = "instance-id: ${var.template_name}-packer\nlocal-hostname: ${var.template_name}-packer\n"
      "/user-data" = local.seed_user_data
    }
    cd_label         = "cidata"
    iso_storage_pool = local.iso_storage_pool
    type             = "ide"
    index            = "3"
    unmount          = true
  }

  ssh_username         = local.build_username
  ssh_private_key_file = var.ssh_private_key_file
  ssh_timeout          = "30m"
}

build {
  sources = ["source.proxmox-clone.cloud"]

  provisioner "ansible" {
    playbook_file    = "${path.root}/../../ansible/cloud_configure.yml"
    user             = local.build_username
    extra_arguments  = ["-e", "cloud_timezone=${var.ks_timezone}", "-e", "cloud_build_username=${local.build_username}"]
    ansible_env_vars = ["ANSIBLE_CONFIG=${path.root}/../../../../ansible.cfg", "OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES", "ANSIBLE_HASHI_VAULT_VALIDATE_CERTS=false"]
  }

  post-processor "shell-local" {
    environment_vars = [
      "PROXMOX_URL=${local.proxmox_url}",
      "PROXMOX_USERNAME=${local.proxmox_user}",
      "PROXMOX_PASSWORD=${local.proxmox_password}",
      "PROXMOX_NODE=${local.proxmox_node}",
      "PROXMOX_VM_ID=${var.vm_id}",
    ]
    command = "${path.root}/../../common/scripts/finalize-template-config.py"
  }
}

variable "proxmox_url" {
  type        = string
  description = "Proxmox API URL, e.g. https://proxmox.example.com:8006/api2/json"
  default     = null
}

variable "proxmox_user" {
  type        = string
  description = "Proxmox API user, e.g. root@pam"
  default     = null
}

variable "proxmox_password" {
  type        = string
  description = "Proxmox API password"
  sensitive   = true
  default     = null
}

variable "proxmox_node" {
  type        = string
  description = "Proxmox node name"
  default     = null
}

variable "storage_pool" {
  type        = string
  description = "Proxmox storage pool name"
  default     = null
}

variable "iso_storage_pool" {
  type        = string
  description = "Proxmox storage pool for temporary Packer seed ISO"
  default     = null
}

variable "bridge" {
  type        = string
  description = "Proxmox bridge name"
  default     = "vmbr0"
}

variable "vlan_tag" {
  type        = number
  description = "Proxmox VLAN tag for the template NIC"
  default     = 10
}

variable "clone_vm_id" {
  type        = number
  description = "VMID of the imported cloud-image base template"
}

variable "vm_id" {
  type        = number
  description = "Proxmox VMID for the final cloud image template"
}

variable "template_name" {
  type        = string
  description = "Final Proxmox template name"
}

variable "tags" {
  type        = string
  description = "Semicolon-separated Proxmox tags for the template"
  default     = "cloud-init;packer"
}

variable "rhel_subscription" {
  type        = bool
  description = "Register with RHN at cloud-init time (required for RHEL cloud images)"
  default     = false
}

variable "memory_mb" {
  type        = number
  description = "Template VM memory in MiB"
  default     = 4096
}

variable "cores" {
  type        = number
  description = "Template VM cores"
  default     = 2
}

variable "build_username" {
  type        = string
  description = "Cloud-init user used by Packer for provisioning"
  default     = null
}

variable "ssh_private_key_file" {
  type        = string
  description = "Path to the private key injected by Packer for provisioning"
  default     = "~/.ssh/id_ed25519"
}

variable "ssh_public_key_build" {
  type        = string
  description = "Ephemeral public key generated by build.py for Packer clone provisioning"
  default     = null
}

variable "ks_language" {
  type        = string
  description = "Shared Linux build variable; unused by cloud-image clone builds"
  default     = null
}

variable "ks_keyboard" {
  type        = string
  description = "Shared Linux build variable; unused by cloud-image clone builds"
  default     = null
}

variable "ks_timezone" {
  type        = string
  description = "Shared Linux build variable; unused by cloud-image clone builds"
  default     = null
}
